### ISSUE TITLE
Paste option not showing

### ISSUE THREAD

**Issue by joethegit** [damat/ImageAboveText#1]
Thanks for creating this.  I really miss the "free floating" image option in Word.

I've installed the add on, but see only Help when I choose it-- screen shot attached. 
![ImageAbove](https://user-images.githubusercontent.com/17802564/71646826-51672c80-2caa-11ea-9690-cd85b4246f3e.png)
See any error I'm making?

Thanks again. 

Joe

**Comment by damat** [comment]
I'm so sorry for missing this issue =((( The only thing I can suggest here is removing and adding the add-on back. Please be sure to grant all required permissions.
