### ISSUE TITLE
Image above text for google docs doesn't work for Scribble drawing

### ISSUE THREAD

**Issue by benjaminszabo** [damat/ImageAboveText#3]
Hi,
wanted to insert signature in google docs and place it on the signature line. Created a Drawing in google docs - Scribble drawing and inserted it in the doc. Selected the drawing and applied the addon and still doesn't work. Text wrapping is "In line with text", page is refreshed, tried both in MS Edge and in Chrome. No success.

Please suggest.
Thank you ,
Benjamin

**Comment by dbarev** [comment]
I have the same experience .... addon works with an image file inserted in document but not with scribble drawing ...

**Comment by zulman** [comment]
Hello,

I know it doesn't make sense but the add-on is built upon a hack of reinserting images into the document. There is no alternative hack for any other type of content like Scribble drawing. I hope someday Google will present an option to place an image above text without any hacks and addons.

Take care, folks!
